<a href="https://colab.research.google.com/github/NastiiaKoval/Machine-Learning/blob/main/%D0%9A%D0%BE%D0%B2%D0%B0%D0%BB%D1%8C_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Варіант 9.

In [6]:
import numpy as np

Завдання 1

Створіть одновимірний масив (вектор) з числами Фібоначчі, де кожне число
дорівнює сумі двох попередніх, та виведіть його значення.


In [2]:
# Функція для генерації чисел Фібоначчі
def fibonacci(n):
    fib_sequence = [0, 1]
    for i in range(2, n):
        fib_sequence.append(fib_sequence[-1] + fib_sequence[-2])
    return np.array(fib_sequence)

# Створення одновимірного масиву з першими 10 числами Фібоначчі
fib_array = fibonacci(10)

# Виведення масиву
print(fib_array)


[ 0  1  1  2  3  5  8 13 21 34]


Завдання 2

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
експонент n^2 для кожного натурального числа n, починаючи з 1, та виведіть його
значення

In [3]:
# Створення матриці 3x3 зі значеннями експонент n^2
matrix = np.array([n**2 for n in range(1, 10)]).reshape(3, 3)

# Виведення матриці
print(matrix)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Завдання 3

Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до
1 та виведіть його значення

In [4]:
array = np.random.uniform(-1, 1, (3, 3))

# Виведення масиву
print(array)

[[-0.8064801  -0.45243734 -0.10026896]
 [-0.22081036 -0.43532709  0.71010519]
 [ 0.79470684  0.08385568  0.8221348 ]]


Завдання 4

 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та знайдіть середнє геометричне всіх елементів.

In [5]:
# Створення масиву 3x3 з випадковими дійсними числами від 0 до 1
array = np.random.uniform(0, 1, (3, 3))

# Обчислення середнього геометричного через numpy
geometric_mean = np.exp(np.mean(np.log(array)))

# Виведення масиву та середнього геометричного
print("Масив:\n", array)
print("Середнє геометричне значення:", geometric_mean)

Масив:
 [[0.94167324 0.67322003 0.07293211]
 [0.45215851 0.92277012 0.56926128]
 [0.16271865 0.34007115 0.25596841]]
Середнє геометричне значення: 0.37746260750042465


Завдання 5

Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними
числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання
та множення

In [7]:
# Створення двох одновимірних масивів з випадковими дійсними числами від -5 до 5
array1 = np.random.uniform(-5, 5, 6)
array2 = np.random.uniform(-5, 5, 6)

# Поелементне додавання
sum_arrays = array1 + array2

# Поелементне віднімання
diff_arrays = array1 - array2

# Поелементне множення
prod_arrays = array1 * array2

# Виведення результатів
print("Перший масив:", array1)
print("Другий масив:", array2)
print("Додавання:", sum_arrays)
print("Віднімання:", diff_arrays)
print("Множення:", prod_arrays)


Перший масив: [-3.49159595 -4.60533477 -4.70422075 -0.55284371  1.48617074 -2.05768802]
Другий масив: [-2.66391227  0.12969606 -3.27218042 -4.83387053 -4.46322323 -0.9874861 ]
Додавання: [-6.15550821 -4.47563871 -7.97640117 -5.38671423 -2.97705249 -3.04517412]
Віднімання: [-0.82768368 -4.73503082 -1.43204033  4.28102682  5.94939397 -1.07020191]
Множення: [ 9.30130527 -0.59729376 15.39305902  2.6723749  -6.63311176  2.03193832]


Завдання 6

Створіть дві матриці 5x5, заповніть їх довільними цілими числами від 1 до 10 та
знайдіть їх добуток.

In [34]:
# Створення двох матриць 5x5 з довільними цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(5, 5))
matrix2 = np.random.randint(1, 11, size=(5, 5))

# Обчислення добутку матриць
matrix_product = np.dot(matrix1, matrix2)

# Виведення матриць та їх добутку
print("Перша матриця (5x5):\n", matrix1)
print("\nДруга матриця (5x5):\n", matrix2)
print("\nДобуток матриць:\n", matrix_product)

Перша матриця (5x5):
 [[ 5  9  2  9  1]
 [ 2  7  9  3  7]
 [ 5  1  5  3  5]
 [ 6  3  6  9  4]
 [ 1 10 10  2  8]]

Друга матриця (5x5):
 [[ 7  1  9  3  5]
 [ 2  8  8  9  3]
 [ 9  9  6  1  3]
 [ 3  2  3  9  6]
 [ 7  9 10  2  1]]

Добуток матриць:
 [[105 122 166 181 113]
 [167 208 207 119  83]
 [126 109 142  66  66]
 [157 138 181 140 115]
 [179 247 235 137  85]]


Завдання 7

Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [33]:
matrix1 = np.random.randint(1, 11, size=(3, 2))

# Створення матриці 2x4 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 4))

# Перемноження матриць
matrix_product = np.dot(matrix1, matrix2)

# Виведення матриць та їх добутку
print("Перша матриця (3x2):\n", matrix1)
print("\nДруга матриця (2x4):\n", matrix2)
print("\nДобуток матриць:\n", matrix_product)

Перша матриця (3x2):
 [[ 5 10]
 [ 6  3]
 [10  2]]

Друга матриця (2x4):
 [[2 4 6 6]
 [8 2 9 8]]

Добуток матриць:
 [[ 90  40 120 110]
 [ 36  30  63  60]
 [ 36  44  78  76]]


Завдання 8

Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [32]:
matrix = np.random.randint(1, 16, size=(2, 2))

# Перевірка, чи матриця є оберненою (детермінант не дорівнює нулю)
det = np.linalg.det(matrix)
if det != 0:
    # Знаходження оберненої матриці
    inverse_matrix = np.linalg.inv(matrix)
    print("Матриця:\n", matrix)
    print("\nОбернена матриця:\n", inverse_matrix)
else:
    print("Матриця не має оберненої (детермінант дорівнює нулю):\n", matrix)


Матриця:
 [[ 9  4]
 [ 3 15]]

Обернена матриця:
 [[ 0.12195122 -0.03252033]
 [-0.02439024  0.07317073]]


Завдання 9

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 7 до 15 та транспонуйте її.

In [31]:
# Створення матриці 3x3 з випадковими цілими числами від 7 до 15
matrix = np.random.randint(7, 16, size=(3, 3))

# Транспонування матриці
transposed_matrix = matrix.T

# Виведення матриці та її транспонованої версії
print("Матриця:\n", matrix)
print("\nТранспонована матриця:\n", transposed_matrix)


Матриця:
 [[ 7  8 13]
 [12  8 13]
 [12 11 12]]

Транспонована матриця:
 [[ 7 12 12]
 [ 8  8 11]
 [13 13 12]]


Завдання 10
Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10 і знайдіть добуток матриці на вектор.

In [30]:
# Створення матриці 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(3, 4))

# Створення вектора 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

# Знаходження добутку матриці на вектор
result = np.dot(matrix, vector)

# Виведення матриці, вектора та їх добутку
print("Матриця:\n", matrix)
print("\nВектор:\n", vector)
print("\nДобуток матриці на вектор:\n", result)


Матриця:
 [[0.33165592 0.51876309 0.36978614 0.1549305 ]
 [0.09686654 0.67783182 0.55897897 0.84255145]
 [0.24178462 0.17755517 0.84697453 0.07328781]]

Вектор:
 [[4]
 [1]
 [8]
 [5]]

Добуток матриці на вектор:
 [[5.57832837]
 [9.74988701]
 [8.28692897]]


Завдання 11

Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [29]:
# Створення матриці 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(2, 3))

# Створення вектора 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Знаходження добутку матриці на вектор
result = np.dot(matrix, vector)

# Виведення матриці, вектора та їх добутку
print("Матриця (2x3):\n", matrix)
print("\nВектор (3x1):\n", vector)
print("\nДобуток матриці на вектор:\n", result)


Матриця (2x3):
 [[0.38282084 0.3205391  0.04743439]
 [0.48234976 0.28116951 0.54825211]]

Вектор (3x1):
 [[10]
 [ 4]
 [ 7]]

Добуток матриці на вектор:
 [[5.44240556]
 [9.78594042]]


Завдання 12

 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.

In [28]:
# Створення двох матриць 2x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Обчислення суми всіх елементів обох матриць
total_sum = np.sum(matrix1) + np.sum(matrix2)

# Виведення матриць та їх загальної суми елементів
print("Перша матриця:\n", matrix1)
print("\nДруга матриця:\n", matrix2)
print("\nСума всіх елементів обох матриць:", total_sum)


Перша матриця:
 [[1 3]
 [4 4]]

Друга матриця:
 [[7 7]
 [6 3]]

Сума всіх елементів обох матриць: 35


Завдання 13

Створіть дві матриці розміром 10x10, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть їх добуток.

In [22]:
# Створення двох матриць 10x10 з випадковими дійсними числами від -2 до 2
matrix1 = np.random.uniform(-2, 2, size=(10, 10))
matrix2 = np.random.uniform(-2, 2, size=(10, 10))

# Обчислення добутку матриць
matrix_product = np.dot(matrix1, matrix2)

# Виведення матриць та їх добутку
print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Добуток матриць:\n", matrix_product)


Перша матриця:
 [[ 1.74917355 -0.9662495  -1.78202846  0.24103024  1.93823895  0.52553504
   1.25094866 -1.25294435  0.586539    1.56114613]
 [ 1.37445523 -1.40492957  0.42470015  0.78525617 -0.13326352 -0.24571537
  -1.57198319 -1.41006527 -0.98374746 -1.09443301]
 [ 1.80525332 -0.29301549 -1.5484235  -0.52404116  0.65827217 -0.92766846
   0.66293873  0.07115637 -1.00268477 -0.69009338]
 [ 0.5605914  -1.14233406 -0.13627682 -0.56229068  0.36471903 -1.70408677
  -0.33669965  0.79028944  1.80321621  1.86273095]
 [ 0.41070109 -0.14357519  0.87052294 -0.33080312 -1.86147514 -0.79450209
   1.96627059 -0.93965089 -0.47283758  0.13296772]
 [ 1.32494608 -1.76016347 -0.14128536 -0.84946813  0.24204678  1.4231515
  -1.57886382 -0.78672357  0.45057028  1.63171403]
 [ 1.52311993  0.49088294  1.50949419  1.80688513 -0.821376   -0.37542912
   1.45862136 -0.52425607  0.78945968 -0.18966106]
 [ 1.19005521  1.00203524  1.88694874 -1.91304472 -0.60825551 -1.25228755
  -0.52144232 -1.53373925 -0.7612476

Завдання 14

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть середнє арифметичне значення елементів матриці.

In [23]:
# Створення матриці 3x3 з випадковими дійсними числами в діапазоні від -1 до 1
matrix = np.random.uniform(-1, 1, size=(3, 3))

# Обчислення середнього арифметичного значення елементів матриці
mean_value = np.mean(matrix)

# Виведення матриці та її середнього арифметичного значення
print("Матриця:\n", matrix)
print("Середнє арифметичне значення елементів матриці:", mean_value)


Матриця:
 [[ 0.86681295  0.25223263  0.70527891]
 [-0.07037409  0.35536834 -0.12684082]
 [ 0.15590526  0.10221875 -0.63978068]]
Середнє арифметичне значення елементів матриці: 0.17786902700072904


Завдання 15

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму квадратів елементів кожного рядка матриці.

In [27]:
# Створення матриці 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(3, 3))

# Обчислення суми квадратів елементів кожного рядка
row_sums_of_squares = np.sum(matrix**2, axis=1).reshape(-1, 1)

# Виведення матриці та вектора-стовпчика з сумами квадратів
print("Матриця:\n", matrix)
print("\nВектор-стовпчик сум квадратів елементів кожного рядка:\n", row_sums_of_squares)


Матриця:
 [[0.13255069 0.45426968 0.33702982]
 [0.60765325 0.31022855 0.9201865 ]
 [0.58723393 0.08596072 0.25725697]]

Вектор-стовпчик сум квадратів елементів кожного рядка:
 [[0.33751973]
 [1.31222742]
 [0.41841408]]
